config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :countries
  resources :customers
  resources :employees
  resources :appoinments
  resources :orders
  resources :wharehouse do
    member do
      get :books, to: 'wharehouse_books#index'
      post :books, to: 'wharehouse_books#create'
    end
  end

  resources :publishers, shallow: true do
    resources :books do
      member do
        get :assets, to: 'book_assets#index'
        post :assets, to: 'book_assets#create'
      end
    end
  end

  resources :invoices, shallow: true do
    collection do
      get :search, to: 'invoice_searches#index'
    end
    resources :payments do
      member do
        get :assets, to: 'payment_assets#index'
        post :assets, to: 'payment_assets#create'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appoinment < ApplicationRecord
  belongs_to :customer
  belongs_to :employee
  has_many :orders
  has_many :invoices, through: :orders
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :attachable, polymorphic: true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  has_many :assets, as: :attachable
  has_many :details
  has_and_belongs_to_many :warehouses

  def self.list
    Book.includes(:publisher).map { |book|  book.list_of_publishers }
  end

  def self.find_title(title, author)
    where("title = ? and author = ?", title, author)
  end

  def list_of_publishers
    "Book: #{title} | Publisher: #{publisher.name}"
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :customers, dependent: :destroy
  has_many :publishers, dependent: :destroy
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :country
  belongs_to :user, optional: true
  has_many :invoices, dependent: :destroy
  has_many :appoinments, dependent: :destroy
  has_many :employees, through: :appoinments

  def self.customer_with_invoices
    joins(invoices: :details)
  end
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :invoice
  belongs_to :book
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :manager, class_name: 'Employee'
  has_many :appoinments
  has_many :customers, through: :appoinments
  has_many :subordinates, class_name: 'Employee', foreign_key: 'manager_id'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :orders
  has_many :appointments, through: :orders
  has_many :details, dependent: :destroy
  has_many :assets, as: :attachable

  after_create :calculate_customer_statement

  scope :paid, -> { where(is_paid: 'true') }
  scope :created_before, ->(time) { where('date < ?', time) }

  private

  def calculate_customer_statement
    # Coolz stuff
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :invoice
  belongs_to :appointment
end

app/models/payment.rb
class Payment < ApplicationRecord
  enum kind: { cash: 0, debit_card: 1 }

  belongs_to :invoice
  has_many :assets, as: :attachable
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  belongs_to :country
  has_many :books, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_one :customer
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_and_belongs_to_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @publisher = Publisher.find_by(id: params[:publisher_id])
    @books = @publisher.books
    @books
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  def index
    @countries = Country.all
  end

  def show
  end

  def new
    @country = Country.new
  end

  def edit
  end

  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to @country, notice: 'Country was successfully created.'
    else
      render :new
    end
  end

  def update
    if @country.update(country_params)
      redirect_to @country, notice: 'Country was successfully created.'
    else
      render :edit
    end
  end

  def destroy
    @country.destroy
    redirect_to countries_url, notice: 'Country was successfully destroyed.'
  end

  private

  def set_country
    @country = Country.find(params[:id])
  end

  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/invoice_searches_helper.rb
module InvoiceSearchesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/countries/edit.html.haml
%h1 Editing Country

= form_with(model: @country, local: true) do |form|
  - if @country.errors.any?
    #error_explanation
      %h2
        = pluralize(@country.errors.count, "error")
        prohibited this country from being saved:
      %ul
        - @country.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

= link_to 'Show', @country
|
= link_to 'Back', countries_path

app/views/countries/index.html.haml
%p#notice= notice
%h1 Countries
%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"}
  %tbody
    - @countries.each do |country|
      %tr
        %td= country.name
        %td= link_to 'Show', country
        %td= link_to 'Edit', edit_country_path(country)
        %td= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New country', new_country_path

app/views/countries/new.html.haml
%h1 New Country

= form_with(model: @country, local: true) do |form|
  - if @country.errors.any?
    #error_explanation
      %h2
        = pluralize(@country.errors.count, "error")
        prohibited this country from being saved:
      %ul
        - @country.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit
= link_to 'Back', countries_path

app/views/countries/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @country.name

= link_to 'Edit', edit_country_path(@country)
|
= link_to 'Back', countries_path